# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
- master

resources:
- repo: self
queue:
  name: Hosted macOS
steps:
- task: GoTool@0
  displayName: 'Use Go 1.10'


- task: Go@0
  displayName: 'go get'
  inputs:
    arguments: '-d'


- task: Go@0
  displayName: 'go build'
  inputs:
    command: build

    arguments: '-o "$(System.TeamProject).exe"'