#!/bin/bash 
#
# Updated script to annotate remarkable files. Original created by:
#
# Copyright © 2018, Eric S Fraga, e.fraga@ucl.ac.uk
# $Id: rmannotated.sh,v 1.12 2018/10/07 15:19:09 ucecesf Exp $
# Log at the end of this file.
#


# Parse input
base=$1
id=$2
output=$3

# Open folder that contains the .rm files
cd ${base}

# Write annotated pdf
doc="${id}.pdf"
if [ -f ${doc} ]
then
    # Get width and height of pdf
    width=$(pdfinfo ${doc} | grep 'Page size:' | awk '{print $3}')
    height=$(pdfinfo ${doc} | grep 'Page size:' | awk '{print $5}')

    # Special handling if rotated
    if (( $(echo "$height > $width" | bc -l) ))
    then
        rotated="no"
    else
        echo 'PDF file is rotated'
        rotated="yes"
        swap=$width
        width=$height
        height=$swap
    fi
else
    rotate="no"
    width=1404
    height=1872
fi

# Create svg files
../rM2svg -c -i "${id}" --width ${width} --height ${height} -o ""


page=0
for svg in *.svg 
do
    p=$(basename $svg .svg)
    rsvg-convert -f pdf -o ${id}_$p.pdf $p.svg
    if [ "$rotated" == "yes" ]
    then
        pdf270 $p.pdf 2>/dev/null
        mv $p-rotated270.pdf $p.pdf
    fi
done


pdfunite ${id}_*.pdf ${id}_annotations.pdf
if [ -f ${doc} ]; then
    pdftk ${doc} multistamp ${id}_annotations.pdf output ${output}.pdf
else
    mv ${id}_annotations.pdf annotated_${id}.pdf
fi

rm ${id}_*.pdf