#!/bin/bash 
#
# Script to annotate remarkable notebooks. Based on the work of:
#   Copyright © 2018, Eric S Fraga, e.fraga@ucl.ac.uk
#   $Id: rmannotated.sh,v 1.12 2018/10/07 15:19:09 ucecesf Exp $  
#
# Changed by peer david for the usage of rmapi
#


# Parse input and set defaults
base=$1
id=$2
output=$3
rM2svg=$4
templatesdir="${HOME}/Documents/Remarkable/Templates"

# Open folder that contains the .rm files
cd ${base}

# Write annotated pdf
doc="${id}.pdf"
if [ -f ${doc} ]
then
    # Get width and height of pdf
    width=$(pdfinfo ${doc} | grep 'Page size:' | awk '{print $3}')
    height=$(pdfinfo ${doc} | grep 'Page size:' | awk '{print $5}')

    # comparing floating point numbers in bash directly is not possible
    if (( $(echo "$height > $width" |bc -l) )); then
        rotated="no"
    else
        rotated="yes"
        swap=$width
        width=$height
        height=$swap
    fi

    usetemplates="no"
else
    rotate="no"
    width=1404
    height=1872

    if [ -d "${templatesdir}" ];
    then
        usetemplates="yes"
    else
        usetemplates="no"
    fi
fi

# Create svg files
$rM2svg -c -i ${id} --width ${width} --height ${height} -o ""

# Read possible templates 
if [ "$usetemplates" == "yes" ];
then
    readarray -t templates < "$id.pagedata"
fi

# Create a pdf for every svg file
page=0
for svg in *.svg 
do
    p=$(basename $svg .svg)

    if [ "$usetemplates" == "yes" ] && [ "${page}" -lt "${#templates[@]}" ];
    then    
        #rsvg-convert -f pdf -o template.pdf "${templatesdir}/${templates[$page]}.svg"
        #rsvg-convert -f pdf -o "${id}_$p_tmp.pdf" "$p.svg"
        inkscape "${templatesdir}/${templates[$page]}.svg" --export-pdf=template.pdf
        inkscape "$p.svg" --export-pdf="${id}_$p_tmp.pdf"

        # Merge
        pdftk "${id}_$p_tmp.pdf" background "template.pdf" output "${id}_$p.pdf"
        rm "${id}_$p_tmp.pdf"
    else
        #rsvg-convert -f pdf -o ${id}_$p.pdf $p.svg
        inkscape "$p.svg" --export-pdf="${id}_$p.pdf"
    fi

    if [ "$rotated" == "yes" ] 
    then
        pdf270 $p.pdf 2>/dev/null
        mv $p-rotated270.pdf $p.pdf
    fi
    page=$((page+1))
done


pdfunite ${id}_*.pdf ${id}_annotations.pdf
if [ -f ${doc} ]; then
    pdftk ${doc} multistamp ${id}_annotations.pdf output ../"${output}.pdf"
else
    mv ${id}_annotations.pdf ../"${output}.pdf"
fi

rm ${id}_*.pdf